[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared", features = ["uuid"] }
macros = { path = "../macros" }
machineid-rs = "1.2.4"
tokio = { version = "1.37.0", features = ["full"] }
