[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["full"] }


shared = { path = "../shared", features = ["uuid"] }
macros = { path = "../macros" }
